### ISSUE TITLE
Data Processing does not account for double carriage returns

### ISSUE THREAD

**Issue by gazkikouken** [IndianaBiosciences/toxapp#33]
We do not account for double CR when reading files, errors out on step one. Add a check or best case fix the file mid pipeline

**Comment by bradjmills** [comment]
Seeing some Step 1a errors from above, but also an occasional Step 1b error in the log files.  Suspect that they are similar issues, but I think I can come up with a 1b example if you can't confirm or reproduce.  Thanks.
