### ISSUE TITLE
Revisit BMD logging in completion email

### ISSUE THREAD

**Issue by bradjmills** [IndianaBiosciences/toxapp#49]
Looks like BMD steps are being logged and/or returning in a confusing order,
e.g. the following output:

Step 5f Completed: Correlations to PathNR processed and loaded
Step 6b Completed: BMD Calculation
Step 6C Completed: BMD pathway results parsed
Step 6 Completed: BMD results generated
All computations sucessfully completed.

6a is missing, 6C is capitalized, successfully is misspelled, and the message for when BMD is not needed is missing a line feed, i.e.

No BMD input files prepared; no suitable multi-concentration experimentsAll computations sucessfully completed.

**Comment by gazkikouken** [comment]
Fixed with a push to dev branch
